{
  "specName": "__all",
  "title": "should login and go to dashboard DE",
  "suiteName": "Dashboard DE",
  "testName": "Dashboard DE should login and go to dashboard DE",
  "testError": "Module build failed (from ./node_modules/babel-loader/lib/index.js):\nError: [BABEL] /app/src/components/Buttons/index.jsx: Cannot find module '@babel/parser'\nRequire stack:\n- /app/node_modules/@babel/core/lib/index.js\n- /app/node_modules/babel-loader/lib/index.js\n- /app/node_modules/loader-runner/lib/loadLoader.js\n- /app/node_modules/loader-runner/lib/LoaderRunner.js\n- /app/node_modules/webpack/lib/NormalModule.js\n- /app/node_modules/webpack/lib/NormalModuleFactory.js\n- /app/node_modules/webpack/lib/Compiler.js\n- /app/node_modules/webpack/lib/webpack.js\n- /app/node_modules/react-scripts/scripts/start.js\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:690:27)\n    at Module.require (internal/modules/cjs/loader.js:852:19)\n    at require (internal/modules/cjs/helpers.js:74:18)\n    at _parser (/app/node_modules/@babel/core/lib/index.js:181:16)\n    at Object.get [as tokTypes] (/app/node_modules/@babel/core/lib/index.js:46:12)\n    at Function.assign (<anonymous>)\n    at /app/node_modules/@babel/core/lib/config/full.js:163:24\n    at cachedFunction (/app/node_modules/@babel/core/lib/config/caching.js:32:19)\n    at loadPluginDescriptor (/app/node_modules/@babel/core/lib/config/full.js:201:28)\n    at /app/node_modules/@babel/core/lib/config/full.js:71:20\n    at Array.reduce (<anonymous>)\n    at recurseDescriptors (/app/node_modules/@babel/core/lib/config/full.js:69:38)\n    at loadFullConfig (/app/node_modules/@babel/core/lib/config/full.js:109:6)\n    at /app/node_modules/@babel/core/lib/transform.js:28:33\n    at processTicksAndRejections (internal/process/task_queues.js:75:11)\n\nThis error originated from your application code, not from Cypress.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.\n\nhttps://on.cypress.io/uncaught-exception-from-application",
  "testCommands": [
    "visit http://localhost:3001"
  ],
  "screenshot": "should-login-and-go-to-dashboard-de-failed.png"
}
